### PR TITLE
small changes in yf_live_prices and add yf_get_dividends()

### PR DESCRIPTION
**Pull request by henrique1008**
I add a daily_change and last price in yf_live_prices() and create a new function to get dividends from stocks.

### CODE REVIEW

**Comment by msperlin** [comment]
Thanks again Henrique. I'll have a look.

**Comment by msperlin** [comment]
The CHECK process indicates many problems with the new function:

image

Can you please fix all errors and warnings (the notes is not trivial and I can fix it). Simply update the branch with he changes. Thanks.

**Comment by henrique1008** [comment]
I fixed some things, I think everything is fine now, I runned check and it´s ok, sorry about this

**Comment by msperlin** [comment]
Thanks. I'll have  alook.

**Comment by msperlin** [comment]
Looks good Henrique. Thanks again. Its on the main branch now.
I'll run some tests on GH and send it to CRAN soon.

**Pull request merged**
